### PR TITLE
Merge20150601

### PR DESCRIPTION
**Pull request by richardlford**
Merge up to tip of LLVM master

There were no merge conflicts.

### CODE REVIEW

**Comment by richardlford** [comment]
This is what the FI job would have done if the debug leg had not had tests timing out.
Locally a checked-build successfully passed testing.
The FI job will be changed to use checked build rather than debug build.

**Comment by JosephTremoulet** [comment]
This looks like it merged the `MS` branch into `master`.  I would have expected the reverse.  Am I just confused and/or reading it wrong?

**Comment by AndyAyersMS** [comment]
Yes, this modifies master. @richardlford you are going to have to undo this.

**Comment by JosephTremoulet** [comment]
Ok.  Likewise microsoft/clang#4, then.

**Comment by richardlford** [comment]
Oop. I’ll take care of this.

**Pull request merged**
