### PR TITLE
Revert cosmetic changes

### PR DESCRIPTION
**Pull request by JosephTremoulet**
Undo some formatting changes and remove one useless #include, to get rid of
some noise when diffing MS branch against master.

### CODE REVIEW

**Comment by JosephTremoulet** [comment]
@russellhadley PTAL

**Comment by AndyAyersMS** [comment]
@swaroop-sridhar changed the casing in the orc code to pass our formatting checks, so I think you may run into this too -- not clear to me if the formatting will run if there is a build failure, and since we have to make LLILC changes to avoid the latter, this is a bit tricky to show in the lab.

**Comment by JosephTremoulet** [comment]
Oops.  Thanks for catching that.  I've reverted the orc casing change.

**Comment by AndyAyersMS** [comment]
Remainder LGTM.

**Pull request merged**
