### PR TITLE
Fix issue in inline alloca expansion.

### PR DESCRIPTION
**Pull request by AndyAyersMS**
Marking RAX as live in to each block in the expansion is not enough to keep it live through the block. Since we don't need to precolor this resource, just use a virtual register to capture the incoming RAX instead.

### CODE REVIEW

**Comment by AndyAyersMS** [comment]
@pgavlin PTAL (note this must go in before the CoreCLR test is added).

**Comment by pgavlin** [comment]
Does this produce any diff in the generated code?

**Comment by AndyAyersMS** [comment]
Yes, without this the test I am adding to CoreCLR will fail because RAX gets trashed in the middle of the expansion.

**Comment by pgavlin** [comment]
*facepalm*

OK, of course. Thanks.

**Comment by pgavlin** [comment]
LGTM.

**Pull request merged**
