### PR TITLE
[WinEH] Update CoreCLR EH state numbering

### PR DESCRIPTION
**Pull request by JosephTremoulet**
Fix the CLR state numbering to generate correct tables for the new funclet
EH representation, and update the lit test to verify them.

Functionally, there are four changes:
 - Arity of cleanuppad parameters needs to use getNumArgOperands() instead
   of getNumOperands() now that cleanuppad has a parent token operand.
 - We assign a catchswitch the state of its first catch, not its unwind
   destination.
 - Don't queue catchpads' users -- this could visit handlers for inner
   tries before handlers for outer tries, and we'll visit everything we
   need to, in correct order, by queuing pads' predecessors. Change the
   initial worklist conditions from isToplevelPadForMSVC to a suitably
   implemented isToplevelPadForCLR accordingly.
 - Adjust getEHPadFromPredecessor to allow CLR state numbering to call it
   and have preds returned regardless of their parentage.

Also change some variable names to improve readability.

### CODE REVIEW

**Comment by JosephTremoulet** [comment]
The current situation of FIs from LLVM is that #122 reports failures, due at least in part to dotnet/llilc#970, though dotnet/llilc#970 seems to be the result of changes to dotnet/coreclr, and so affecting llilc even without the FI.  Meanwhile, [r255422](http://reviews.llvm.org/rL255422) (aka 8cec2f281696a19f) changed the set of EH opcodes (and related IR construction APIs), so we can't integrate that wihtout dotnet/llilc#968.  The CLR-specific logic in [r255422](http://reviews.llvm.org/rL255422) (aka 8cec2f281696a19f) is incorrect, so if we just integrate that and merge dotnet/llilc#968, we'll regress the pass rate of the --eh mode (and so make it harder to triage eh-related failures while resolving dotnet/llilc#970 ).  The fix for CLR-specific logic is up for review (to the upstream LLVM tree) as [D15325](http://reviews.llvm.org/D15325).  It would be nice to get merge in [D15325](http://reviews.llvm.org/D15325) at the same time as [r255422](http://reviews.llvm.org/rL255422) (aka 8cec2f281696a19f) and dotnet/llilc#968, but [D15325](http://reviews.llvm.org/D15325) depends on [r255422](http://reviews.llvm.org/rL255422) (aka 8cec2f281696a19f) (and isn't upstream yet). This PR consists of a merge that includes [r255422](http://reviews.llvm.org/rL255422) (aka 8cec2f281696a19f) plus a straight cherry-pick of [D15325](http://reviews.llvm.org/D15325) (as its final commit, a5279f43039c383).

One way to go forward, given that dotnet/llilc#970 seems to be an independent issue, would be to push up this merge (54d20f1ecc7de0c7a2) and then merge both this PR and dotnet/llilc#968, so that everything builds and the --eh mode shouldn't be regressed, then pursue dotnet/llilc#970 on top of the latest bits.

Another way forward would be to get dotnet/llilc#970 fixed first, then re-run tests on #122 to make sure it doesn't introduce new issues, merge it and only then pull in [r255422](http://reviews.llvm.org/rL255422) (aka 8cec2f281696a19f) + dotnet/llilc#968 + this/[D15325](http://reviews.llvm.org/D15325).

@AndyAyersMS / @richardlford, I'm curious what you think is best.

**Comment by AndyAyersMS** [comment]
I guess I was thinking the latter, not really looking ahead to more blocking issues updating LLVM bits. 

I am hoping to have dotnet/llilc#970 fixed sometime later today, then we can retest #122, then I'd rely on your expertise to decide how to move the LLVM side forward.

Note we may be blocked even with exclusions if the new tests push us past the timeouts.

**Comment by JosephTremoulet** [comment]
@AndyAyersMS sure, that sounds good.  Once you get #122 in, then, I think it makes sense to check in another FI, dotnet/llilc#968, and this change all at once.  Checking in this change is somewhat speculative since [D15325](http://reviews.llvm.org/D15325) is still in review, but I think it makes sense to unblock LLILC in the meantime and then once the upstream review completes and the change gets checked in and FIed back down, we can resolve to any conflicts to keep the upstream version. With all that in mind, could you PTAL this change?  I'll have to rebase it before merging, but just looking at a5279f4 will show the correct ultimate diff.

**Comment by AndyAyersMS** [comment]
Can't seem to leave inline comments, so I'll summarize what I saw looking at the diffs for `a5279f4`.

lib\codegen\winehprepare 475: I don't follow why sometimes catchswitch "unwinds to caller" is trusted and other times it is not... (compare vs line 448). Not saying it's wrong, mind you. Is this something that is tested in one of the lit cases?

Otherwise it looks ok to me.

**Comment by AndyAyersMS** [comment]
I've commited dotnet/llilc#971, will restart testing on #122.

**Comment by JosephTremoulet** [comment]
> lib\codegen\winehprepare 475: I don't follow why sometimes catchswitch "unwinds to caller" is trusted and other times it is not... (compare vs line 448). Not saying it's wrong, mind you. Is this something that is tested in one of the lit cases?

Yeah, that's subtle and merits a comment, which I've added (to 836c7e5de33eae).  The issue with catchswitch is that it might be annotated as "unwinds to caller" when really what was known was "never unwinds" -- in the case of line 448, seeing the wrong annotation should just lead to benignly absent EH table entries; in the case of what was line 475, seeing the wrong annotation could have mislead us into leaving out EH table entries that need to be there when an invoke unwinds through the cleanuppad and ought to be caught by another handler in the function.

Regarding tests, we have one lit test which covers a variety of cases of expected / well-formed input.  I plan to add tests for these odd corner cases along with the fix for the issue noted in the FIXME around being able to track down the invokes in a cleanuppad.

**Comment by JosephTremoulet** [comment]
I've updated this to match the latest version of [D15325](http://reviews.llvm.org/D15325), which means expanding the FI to include [r255674](http://reviews.llvm.org/rL255674) aka b46bb541f5f78520b08c1.  Again, the final commit (now ad51af935e86affbdacd) shows the non-FI part.
@AndyAyersMS PTAL.

**Comment by JosephTremoulet** [comment]
This change and dotnet/LLILC#968 will need to go in together; http://dotnet-ci.cloudapp.net/view/dotnet_llilc/job/dotnet_llilc_prtest/1344/ is running a test of the combination.

**Comment by JosephTremoulet** [comment]
> http://dotnet-ci.cloudapp.net/view/dotnet_llilc/job/dotnet_llilc_prtest/1344/ is running a test of the combination.

Those tests are failing, so I've been investigating.  Part of 8cec2f281696a19faee58cd0 has WinEHPrepare build up a map from invokes to "eh states" stored in the WinEHFuncInfo, which is later consulted by SelectionDAGBuilder when lowering invokes.  In LLILC, RewriteStatepointsForGC swoops in between and, for all invokes which are GC safepoints, replaces the original invoke with an invoke of `@llvm.gc.statepoint` that takes the callee as an argument, which severs the connection with the map in the WinEHFuncInfo.  :/

Seems to be a classic case of two different things trying to "run last", but it's not immediately obvious how to improve on that without teaching one directly about the details of the other... maybe the InvokeStateMap should be a ValueMap so that its keys will be rewritten when the safepoint rewriting calls replaceAllUsesWith.

**Comment by JosephTremoulet** [comment]
> maybe the InvokeStateMap should be a ValueMap so that its keys will be rewritten when the safepoint rewriting calls replaceAllUsesWith.

Not that simple; the lookup goes through a `CallLoweringInfo` object that also can't find the original invoke...

**Comment by AndyAyersMS** [comment]
Hmm, side tables strike again.

**Comment by JosephTremoulet** [comment]
I can reproduce this on e.g. JIT\Methodical\explicit\coverage\expl_float_1_r\expl_float_1_r with conservative GC.  @swaroop-sridhar, is it expected that we'd be trying to lower statepoints with conservative GC?

**Comment by swaroop-sridhar** [comment]
Even with conservative GC, Statepoints are inserted and lowered for GC-Transitions.
But the insertion happens in the reader -- `PlaceSafepoints` and `RewriteStatepointsforGC` phases are not run if `DoInsertStatepoints == false`. These statepoints  without any actual gc-pointers tracked within them, and lowered as usual.

**Comment by JosephTremoulet** [comment]
Ah, ok, thanks.  Then the issue is purely that the `CallLoweringInfo` constructed by `lowerStatepoint` doesn't link in the `CallSite`, which `lowerCallOperands` now demands on invokes in functions with funclets.  Need to understand why `lowerStatepoint` is using that overload to construct the `CallLoweringInfo` and whether there's a better channel to pass that information...

**Comment by JosephTremoulet** [comment]
I did some poking around.  The two means of creating CallLoweringInfos (i.e. with and without the CallSite) have existed for as long as CallLoweringInfo has.  The EH state map needs to use InvokeInsts as keys now because there are no longer EndPads and so it can't just use the unwind destination like it did previously.  The InvokeInst is needed in SelectionDAGBuilder::lowerInvokable, which is a private helper method.  It has two callers, one of which is for statepoints and the other of which always passes a CallLoweringInfo with a CallSite.  To me, it makes more sense to just add the InvokeInst as a parameter to the helper, to avoid upsetting expectations in the call lowering code about what it means when a CallLoweringInfo has a CallSite attached to it and to avoid expanding CallLoweringInfo to include EH state map info that's only relevant for funclet EH.  So, I've pushed a change does just that and would like to merge it.  I'd have submitted the same for upstream review, except that it ought to be accompanied by a lit test, and reproducing the error requires a statepoint invoke which unwinds to a funclet EH pad, and the upstream statepoint lowering code fails elsewhere first on that combination -- #106 stubbed out those paths so they don't crash, but I think it makes sense to upstream this change only after the stubs have been replaced with a real implementation (tracked by #105) and that has been upstreamed as well.

@AndyAyersMS PTAL.  The only change is the additional commit.

**Comment by AndyAyersMS** [comment]
Latest commit LGTM.

**Pull request merged**
