### PR TITLE
Merge master after resolving conflicts in SmallBitVector.h

### PR DESCRIPTION
**Pull request by russellhadley**
Handle 64 bit size in applybits in SmallBitVector.h

### CODE REVIEW

**Comment by russellhadley** [comment]
@adiaaida PTAL.  I was loosing .MERGE_HEAD when I was switching branches in the middle of the merge.  Need to switch branches first, then merge.

**Comment by adiaaida** [comment]
Yup, that'd do it.

LGTM

**Comment by russellhadley** [comment]
@dotnet-bot retest this please.

**Comment by russellhadley** [comment]
The only failure is in the test I disabled with https://github.com/dotnet/llilc/pull/861.  Merging this now to unblock upstream merging.

**Pull request merged**
