### PR TITLE
MS

### PR DESCRIPTION
**Pull request by russellhadley**
Hand merge of the MS branch.  Conflict was with the environment enum where a new env clashed with coreclr.

### CODE REVIEW

**Comment by russellhadley** [comment]
@dotnet-bot retest this please

**Comment by adiaaida** [comment]
@dotnet-bot test this please

**Comment by russellhadley** [comment]
@dotnet-bot retest this please

**Comment by adiaaida** [comment]
@dotnet-bot retest this please

**Comment by adiaaida** [comment]
@dotnet-bot retest this please

**Comment by adiaaida** [comment]
@dotnet-bot test this please

**Comment by adiaaida** [comment]
@dotnet-bot test this please

**Comment by adiaaida** [comment]
@dotnet-bot test this please

**Comment by adiaaida** [comment]
@dotnet-bot test this please

**Comment by adiaaida** [comment]
@dotnet-bot test this please

**Pull request merged**
