### PR TITLE
FI

### PR DESCRIPTION
**Pull request by JosephTremoulet**

### CODE REVIEW

**Comment by JosephTremoulet** [comment]
@AndyAyersMS / @russellhadley / whoever, PTAL.  The only conflict was trivial (we have some code in statepoints.h that's indented because it's under an 'if' in our clone; some of that code was changed and the different indent levels constituted a conflict).

**Comment by AndyAyersMS** [comment]
LGTM

**Comment by JosephTremoulet** [comment]
Looks like the test with chk build of llilc timed out, but this time as a whole rather than any individual test timing out:

```
06:50:46     Discovering: Interop.XUnitWrapper
06:50:46     Discovering: readytorun.XUnitWrapper
06:50:47     Discovered:  Interop.XUnitWrapper
06:50:47     Discovered:  readytorun.XUnitWrapper
06:50:47     Starting:    Interop.XUnitWrapper
06:50:47     Starting:    readytorun.XUnitWrapper
06:50:47     Discovering: JIT.XUnitWrapper
06:50:59     Finished:    Interop.XUnitWrapper
06:50:59     Finished:    readytorun.XUnitWrapper
06:51:01     Discovered:  JIT.XUnitWrapper
06:51:01     Starting:    JIT.XUnitWrapper
08:39:03 
Build was aborted
08:39:04 Aborted by anonymous
08:39:08 [BFA] Scanning build for known causes...
08:39:09 ..................[BFA] Found failure cause(s):
08:39:27 [BFA] Build Timed Out from category Timeout
08:39:27 [BFA] Done. 18s
08:39:30 Finished: ABORTED
```

**Comment by JosephTremoulet** [comment]
Here's the same with the elapsed time instead of clock time on the timestamps:

```
01:01:54.524     Discovering: JIT.XUnitWrapper
01:02:06.871     Finished:    Interop.XUnitWrapper
01:02:06.873     Finished:    readytorun.XUnitWrapper
01:02:09.098     Discovered:  JIT.XUnitWrapper
01:02:09.098     Starting:    JIT.XUnitWrapper
02:50:10.863 
Build was aborted
02:50:11.869 Aborted by anonymous
02:50:15.998 [BFA] Scanning build for known causes...
02:50:16.998 ..................[BFA] Found failure cause(s):
02:50:34.648 [BFA] Build Timed Out from category Timeout
02:50:34.648 [BFA] Done. 18s
02:50:37.418 Finished: ABORTED
```

Which shows the build timing out after 2h50m = 170 minutes, which is odd because the Jenkins timeout (which looks like what this was?) is 240 minutes = 4 hours.  I'll see what happens on a re-run of that leg...

**Comment by AndyAyersMS** [comment]
It looks like somebody stopped the job; it did not time out on its own.

**Comment by AndyAyersMS** [comment]
Suspect testing got impacted by the Jenkins reboot.

@dotnet-bot retest this please

**Comment by JosephTremoulet** [comment]
Oops, I'd already started a re-run of the failed leg, but forgot to report the link here.  It's this: http://dotnet-ci.cloudapp.net/job/dotnet_llilc_check_win64_prtest/803/console

And it succeeded, so I'll go ahead and push this up.

**Comment by AndyAyersMS** [comment]
FYI my re-run is hitting failures in newly added tests, so we'll fail on the LLILC side until we get exclusion updates.

**Pull request merged**
