### PR TITLE
Don't omit the constant when computing a cross-section relative reloc…

### LINKED ISSUE #37: Fix issue with cross-section relative symbol relocation
When we try to express a cross-section relative relocation in COFF, LLVM is not including the extra displacement that is involved. For example:
```
@g3 = constant i32 3;
@t1 = global i64 add(i64 sub(i64 ptrtoint(i32* @g3 to i64), i64 ptrtoint(i64* @t1 to i64)  ), i64 4), section ".xxx"
```
Here the intent is to initialize `t1` with the 64 bit relative offset to `g3`, but the actual relocation generated does not include the proper offset.

### PR DESCRIPTION
**Pull request by AndyAyersMS**
…ation.

Closes #37.

### CODE REVIEW

**Comment by AndyAyersMS** [comment]
@kyulee1 PTAL.

**Comment by kyulee1** [comment]
LGTM. Thanks for fixing this!

**Comment by AndyAyersMS** [comment]
I'm going to submit this to LLVM directly -- will close this PR once it comes back in via a merge from master.

**Comment by AndyAyersMS** [comment]
This came in via master at edd2bb8, so closing without merging this PR.

**Pull request closed without merging**
