### PR TITLE
Fi

### PR DESCRIPTION
**Pull request by JosephTremoulet**

### CODE REVIEW

**Comment by JosephTremoulet** [comment]
@swaroop-sridhar PTAL.  Conflicts were mostly straightforward, either picking up changes to parts of RS4GC that we've changed to ignore funclets, and rewriting tests (why do we have tests that differ from upstream only in their CHECK lines?) now that gc.statepoint's return type is `token` rather than `i32`.  The only change aside from those (and some trivial conflicts where we've added calling conventions) was removing [this new assertion](https://github.com/JosephTremoulet/llvm/blob/982aa42a6efd967b7dd0bbb82859f1736072ac56/lib/Transforms/Scalar/RewriteStatepointsForGC.cpp#L459-L461) because we expect to see addrspacecasts, please double-check that that's the right thing to do.

**Comment by JosephTremoulet** [comment]
http://dotnet-ci.cloudapp.net/view/dotnet_llilc/job/dotnet_llilc_prtest/1365/ tests this in conjunction with dotnet/llilc#989, which is needed to accomodate 56afa6e6

**Comment by swaroop-sridhar** [comment]
@JosephTremoulet I could not see the diffs  in this PR (github gave up because of the large number of files). However, I looked at the diffs wrt master branch, and they look OK. I looked at the RewriteStatepointsForGC in JosephTremoulet/FI branch, and the changes look good to me.
Yes, we need to remove the assert() you've mentioned.
Which is the test where we differ only in CHECK lines?

**Comment by JosephTremoulet** [comment]
http://dotnet-ci.cloudapp.net/view/dotnet_llilc/job/dotnet_llilc_prtest/1365/ shows timeouts on hugeexprsimple1, but I think it makes sense to go ahead with the FI and exclude the test if it continues failing

**Comment by JosephTremoulet** [comment]
> Which is the test where we differ only in CHECK lines?

I took another look, and I was wrong about that, sorry.  What's different is that we pass more arguments to gc.statepoint.  Which is also surprising to me that we'd have that difference.

**Pull request merged**
