### PR TITLE
Merge1123

### PR DESCRIPTION
**Pull request by AndyAyersMS**
Eager merge to pick up my frame gen change and unblock tail calls in LLILC.

Had to manually resolve a conflict in test/CodeGen/X86/statepoint-gctransition-call-lowering.ll

### CODE REVIEW

**Comment by AndyAyersMS** [comment]
@pgavlin PTAL

**Comment by pgavlin** [comment]
LGTM.

**Comment by AndyAyersMS** [comment]
Looks like the nightly was able to merge this without issue, so we don't need this.

**Comment by AndyAyersMS** [comment]
Oops, I take that back....

**Comment by AndyAyersMS** [comment]
Was looking at master.. .no merge into MS.

**Pull request merged**
