### PR TITLE
Merge master into MS branch

### PR DESCRIPTION
**Pull request by richardlford**
Manually resolve conflicts in two files with help from @pgavlin. The two files needing resolution were

lib/Target/X86/X86FrameLowering.cpp
lib/Target/X86/X86MCInstLower.cpp

### CODE REVIEW

**Comment by richardlford** [comment]
@pgavlin, PTAL. I had to change the MachineOperand::MO_MachineBasicBlock case some because in its new environment (X86MCInstLower::LowerMachineOperand in X86MCInstLower.cpp) the target variable was no longer available and the results just needed to be returned instead.

**Comment by richardlford** [comment]
A local checked build of these changes passed testing.

**Comment by pgavlin** [comment]
LGTM once the CI is green.

**Comment by richardlford** [comment]
@pgavlin, do you want to take a look at this?

**Comment by pgavlin** [comment]
Looks like the CI failure is due to timeouts in the debug build. @richardlford, you're green to merge.

**Pull request merged**
