### PR TITLE
Merge through r255227

### PR DESCRIPTION
**Pull request by AndyAyersMS**
Manually resolved conflict in `include/llvm/IR/CallingConv.h`

### CODE REVIEW

**Comment by AndyAyersMS** [comment]
@JosephTremoulet PTAL

**Comment by JosephTremoulet** [comment]
You've got all the changes bundled up as one single-parent commit, rather than a merge commit that has the chain up to r255227 / 342c5a64325164d0 as a second parent.

**Comment by AndyAyersMS** [comment]
Is there any info on how to stage this to get what you suggest? I just merged master into a branch off of MS.

Also there are 26 more failing tests....will need to do some more excluding.

**Comment by AndyAyersMS** [comment]
Abandoning this in favor of the `V2` merge.

**Pull request closed without merging**
