### PR TITLE
Merge 12 11 15 v2

### PR DESCRIPTION
**Pull request by AndyAyersMS**

### CODE REVIEW

**Comment by JosephTremoulet** [comment]
LGTM

**Comment by AndyAyersMS** [comment]
@JosephTremoulet PTAL.

CI will fail testing but I'll commit once I see clean builds.

**Comment by AndyAyersMS** [comment]
Looks like lots of test failures in the CI runs.

While some failures (~30) are expected this seems to be way too many. I suspect something in the new LLVM bits has broken things. Will investigate.

**Comment by AndyAyersMS** [comment]
Merge was bad :-(. Updated.

**Comment by AndyAyersMS** [comment]
@dotnet-bot retest this please

**Comment by AndyAyersMS** [comment]
@JosephTremoulet chk has 14 failures, 11 timeouts. Looks like we're not quite ready to go yet. Sorry.

**Comment by AndyAyersMS** [comment]
Let me get the current LLILC clean and I'll see if I can get back to this tonight... but probably it will be tomorrow sometime.

**Comment by AndyAyersMS** [comment]
LLILC exclusions are now up to date. Going to see if I can repro some of those chk timeouts.

**Comment by AndyAyersMS** [comment]
Could not repro them, most of them pass quickly. The ones that caused validation errors (because of botched excludes) popped up dialogs, which explains there timeouts. I really need to stop the dialog popups (dotnet\llilc#582)... anyways this is puzzling but perhaps if one test does pop a dialog it messes up other tests too?  Not sure....

Am going to kick off  a retest with the latest LLILC excludes.

**Comment by AndyAyersMS** [comment]
@dotnet-bot retest this please

**Comment by AndyAyersMS** [comment]
Still not able to repro locally. Lab failures are very consistent.

All the failing tests are interop-related. They all time out. So I suspect there's a dialog box sitting there on the lab machine.

The lab is using VS2013 to build LLILC, while now I'm using VS2015, so will try a build with an older compiler to see if that shakes anything out.

**Comment by JosephTremoulet** [comment]
Actually it looks like the first two failures are the readytorun tests.  Maybe they time out w/ a popup?

**Comment by AndyAyersMS** [comment]
Still trying to repro, no luck yet.

**Comment by AndyAyersMS** [comment]
Cherry-picked r255703 to fix the assert we think is causing popups.

The assert was for an EFLAGS spill coming from gc transition end/pause lowering. We should fix thisgc not to spill the flags. Opened #124.

**Comment by JosephTremoulet** [comment]
@dotnet-bot retest this please (the run kicked off by the cherry-pick failed due to a network error)

**Comment by AndyAyersMS** [comment]
@JosephTremoulet I think we can probably merge this one, the CI failure is win32 release and appears to be infrastructure related.Agree?

**Comment by AndyAyersMS** [comment]
Also I wonder if the mirroring is broken, I thought it was supposed to trail the main LLVM git clone by 5 minutes or so? Last update was 21 hours ago. @adiaaida do you know?

**Comment by JosephTremoulet** [comment]
Interesting, dotnet-bot [kicked off a re-run](http://dotnet-ci.cloudapp.net/job/dotnet_llilc_llvm_prtest/200/console) as requested, but the link here still points to the original run.  The leg that failed in the original has already passed in the re-run, so yes I think we're good to merge.

I'm not sure which step you mean by "the mirroring".  I think that llvm.org exposes a git mirror of the svn repo.  Regardless, I'm pretty sure that the llvm-mirror/llvm project on GitHub updates every five minutes from llvm.org.  Our CI jobs pull from llvm-mirrof/llvm to Microsoft/llvm once per day.

**Comment by JosephTremoulet** [comment]
I should clarify -- pulling from llvm-mirror/llvm's master branch to Microsoft/llvm's master branch happens daily.  (which is the same cadence as the automated attempted integrations from Microsoft/llvm's master branch to Microsoft/llvm's MS branch)

**Comment by AndyAyersMS** [comment]
Guess I confused the cadence of LLVM.org's SVN->llvm-mirror/llvm with llvm-mirror/llvm -> microsoft/llvm.

Hopefully the cherry-pick doesn't cause trouble. I got the hash by fetching the commit history from llvm.org.

Merging.

**Pull request merged**
