### PR TITLE
chkstk merge

### PR DESCRIPTION
**Pull request by russellhadley**
Merge to handle changes for inlining chkstk in prologs that was upstreamed by @AndyAyersMS

### CODE REVIEW

**Comment by russellhadley** [comment]
@AndyAyersMS PTAL.

**Comment by AndyAyersMS** [comment]
lib/Target/X86/X86FrameLowering.h is not right -- there are two copies of the emitStackProbe* declarations. You should take the version from master.

**Comment by russellhadley** [comment]
Yeah.  I saw.  Automerge messed that up somehow.  I made the change and updated the branch.

**Comment by AndyAyersMS** [comment]
LGTM

**Pull request merged**
