### PR TITLE
FI

### PR DESCRIPTION
**Pull request by JosephTremoulet**
Conflicts are simple "resolve theirs" where some of the new commits re-touch files included in our cherry-pick.

### CODE REVIEW

**Comment by AndyAyersMS** [comment]
LGTM

**Comment by JosephTremoulet** [comment]
Looks like some of the auto-merged code didn't merge correctly, so there are build failures; will fix.  But there's also this build failure on the linux-release job:

```
/mnt/j/workspace/dotnet_llilc_linux_release_prtest/coreclr/src/jit/flowgraph.cpp:4640:27: error: ISO C++11 does not allow conversion from string literal to 'char *' [-Werror,-Wwritable-strings]
                 message = "Unsupported opcode for inlining";
                          ^
```

Andy, looks like that's from dotnet/coreclr@ebbea0a31a72c0d455 probably?  Don't know why we wouldn't be hitting the same error in coreclr CI jobs...

**Comment by AndyAyersMS** [comment]
Hmm, yeah, that's odd. It's an easy enough fix.

**Comment by JosephTremoulet** [comment]
Testing completed with only the failures that dotnet/llilc#1026 fixes, so I'll go ahead and push this up.

**Pull request merged**
