### PR TITLE
FI debug symbol header into MS branch

### PR DESCRIPTION
**Pull request by hoyMS**
Whole FI from master to MS is blocked. Merging the debug symbol support first. 

[llvm-readobj] Add support for dumping S_DEFRANGE symbols
git-svn-id: https://llvm.org/svn/llvm-project/llvm/trunk@259719 91177308-0d34-0410-b5e6-96231b3b80d8

### CODE REVIEW

**Comment by hoyMS** [comment]
@AndyAyersMS @kyulee1 PTAL

**Comment by AndyAyersMS** [comment]
LGTM

**Comment by kyulee1** [comment]
LGTM

**Comment by hoyMS** [comment]
Thanks for reviewing. Can any of you merge the change for me? It appears that I don't have write access.

**Pull request merged**
